server:
  port : 8099

spring:
  datasource:
    password: Scout81.
    url: jdbc:postgresql://localhost:5432/hts
    username: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

city:
  csv:
    path: /Users/ersingureli/Desktop/tasklar ve dokumanlar/hts/il_ilce.csv

google:
  api:
    key: AIzaSyBxZ4cEcN2i-xaiiDbsjf8vVxvaGr7hEmc

geoapify:
  api:
    key: 55efb1688fbe40da880033bd7694ff71

hts:
  analyse:
    interval-minutes: 10